<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/Data-_Visualization/blob/main/data_cleanining_for%20davis_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **Data cleaning**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving enterprise_retail_dataset.xlsx to enterprise_retail_dataset (1).xlsx

In [ ]:
df = pd.read_excel("enterprise_retail_dataset.xlsx")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             94940 non-null   object
 1   Order_Date           94998 non-null   object
 2   Delivery_Date        94923 non-null   object
 3   Customer_ID          95028 non-null   object
 4   Customer_Age         100000 non-null  float64
 5   Gender               95078 non-null   object
 6   Country              95001 non-null   object
 7   State                95043 non-null   object
 8   City                 94921 non-null   object
 9   Region               94987 non-null   object
 10  Category             94976 non-null   object
 11  Sub_Category         94943 non-null   object
 12  Product_Name         94955 non-null   object
 13  Quantity             94986 non-null   float64
 14  Unit_Price           94891 non-null   float64
 15  Sales                94939 non-null   float64
 16  Cost                 95053 non-null   float64
 17  Profit               100000 non-null  float64
 18  Discount_Percentage  95009 non-null   float64
 19  Payment_Method       95025 non-null   object
 20  Shipping_Mode        95160 non-null   object
 21  Delivery_Time_Days   95020 non-null   float64
 22  Return_Status        94994 non-null   object
 23  Customer_Segment     94925 non-null   object
 24  Rating               100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [18]:
df.isnull().sum()

Order_ID               5060
Order_Date             5002
Delivery_Date          5077
Customer_ID            4972
Customer_Age              0
Gender                 4922
Country                4999
State                  4957
City                   5079
Region                 5013
Category               5024
Sub_Category           5057
Product_Name           5045
Quantity               5014
Unit_Price             5109
Sales                  5061
Cost                   4947
Profit                    0
Discount_Percentage    4991
Payment_Method         4975
Shipping_Mode          4840
Delivery_Time_Days     4980
Return_Status          5006
Customer_Segment       5075
Rating                    0
dtype: int64

In [19]:
df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].median())

df['Profit'] = df['Profit'].fillna(df['Profit'].median())

df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [20]:
df['Payment_Method'] = df['Payment_Method'].fillna(
    df['Payment_Method'].mode()[0]
)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['Category'].unique()

array(['Clothing', 'Home & Lifestyle', 'Electronics', nan], dtype=object)

In [23]:
df['Payment_Method'].unique()

array(['Paypal', 'PayPal', 'credit card', 'Credit Card'], dtype=object)

In [24]:
df[(df['Customer_Age'] < 18) | (df['Customer_Age'] > 80)]

,Order_ID,Order_Date,Delivery_Date,Customer_ID,Customer_Age,Gender,Country,State,City,Region,...,Sales,Cost,Profit,Discount_Percentage,Payment_Method,Shipping_Mode,Delivery_Time_Days,Return_Status,Customer_Segment,Rating
3,ORD0000003,2023-06-29 23:05:13,2023-07-03 23:05:13,CUST00003,11.0,Male,USA,TX,Bangalore,North America,...,136.95,105.40,31.55,5.0,Paypal,Express,4.0,Not Returned,Corporate,5.0
9,ORD0000009,2023-09-16 04:37:15,2023-09-19 04:37:15,CUST00009,12.0,Male,India,Berlin,SF,Europe,...,371.11,336.91,34.20,10.0,Paypal,Express,3.0,Not Returned,Corporate,4.0
14,ORD0000014,2023-12-28 12:32:20,2024-01-06 12:32:20,CUST00014,12.0,Male,Germany,MH,Berlin,North America,...,1975.30,1558.86,416.44,20.0,Paypal,Standard,9.0,Not Returned,Consumer,3.0
32,ORD0000032,2024-06-20 18:02:33,2024-06-23 18:02:33,CUST00032,12.0,Female,Germany,NaN,LA,Europe,...,1940.14,1593.96,346.18,5.0,Paypal,Express,3.0,Not Returned,Corporate,4.0
72,ORD0000072,NaN,2023-07-26 17:56:27,CUST00072,-5.0,NaN,India,KA,Bangalore,North America,...,1321.36,1190.52,130.84,20.0,credit card,Express,4.0,Not Returned,Corporate,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99798,ORD0099798,2024-03-15 18:26:07,NaN,NaN,15.0,Other,Germany,KA,Mumbai,North America,...,74.58,70.72,3.86,20.0,Paypal,Express,3.0,Not Returned,Consumer,3.0
99840,ORD0099840,2024-09-20 21:44:37,2024-09-27 21:44:37,CUST49840,15.0,Other,USA,TX,Bangalore,North America,...,195.98,116.43,79.54,10.0,Paypal,Standard,7.0,Not Returned,Consumer,5.0
99876,ORD0099876,2024-07-23 08:57:07,2024-07-29 08:57:07,CUST49876,12.0,NaN,USA,NaN,SF,Europe,...,233.84,169.04,64.81,5.0,Paypal,Standard,6.0,Not Returned,Corporate,3.0
99885,NaN,2024-08-06 20:51:15,2024-08-15 20:51:15,CUST49885,1.0,Other,India,Berlin,Berlin,North America,...,465.21,437.21,28.00,NaN,credit card,Standard,9.0,Not Returned,Corporate,3.0
99946,ORD0099946,2023-10-15 07:01:43,2023-10-18 07:01:43,CUST49946,9.0,Other,Germany,TX,NaN,North America,...,892.11,485.22,406.89,10.0,Paypal,Express,3.0,Not Returned,Consumer,4.0

In [25]:
median_age = df['Customer_Age'].median()

df.loc[
    (df['Customer_Age'] < 18) |
    (df['Customer_Age'] > 80),
    'Customer_Age'
] = median_age

In [26]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

In [27]:
df[['Order_Date','Delivery_Date']].dtypes

Order_Date       datetime64[ns]
Delivery_Date    datetime64[ns]
dtype: object

In [30]:
df.to_excel("cleaned_enterprise_retail_dataset.xlsx", index=False)

In [31]:
from google.colab import files
files.download("cleaned_enterprise_retail_dataset.xlsx")